[plugins]
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[versions]
# Paper API
paper = "1.21.1-R0.1-SNAPSHOT"
velocity = "3.3.0-SNAPSHOT"
minecraft = "1.21.1"
brigadier = "1.3.10"

# Gradle Plugins
paperweight = "1.7.3"
runPaper = "2.3.0"
minotaur = "2.8.7"
hangar = "0.1.2"
shadow = "8.3.0"

# Common API
triumph-cmd = "2.0.0-ALPHA-10"
jetbrains = "24.1.0"
adventure = "4.17.0"
cloud-release = "2.0.0"
cloud-beta = "2.0.0-beta.10"
gson = "2.10.1"
jalu = "1.4.1"

# Vital API
vital-common = "0.0.6"
vital-paper = "1.0.6"

[libraries]
# Velocity API
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }

# Mojang API
brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }

# Paper API
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

# Kyori API
kyori-logger = { module = "net.kyori:adventure-text-logger-slf4j", version.ref = "adventure" }
kyori-text = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
kyori-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }

# Cloud API
cloud-extras = { module = "org.incendo:cloud-minecraft-extras", version.ref = "cloud-beta" }
cloud-paper = { module = "org.incendo:cloud-paper", version.ref = "cloud-beta" }

# Bukkit Plugins API
placeholderapi = { group = "me.clip", name = "placeholderapi", version = "2.11.5" }
essentials = { group = "net.essentialsx", name = "EssentialsX", version = "2.20.1" }
vault = { group = "com.github.MilkBowl", name = "VaultAPI", version = "1.7.1" }

# Vital API
vital-common = { module = "com.ryderbelserion.vital:common", version.ref = "vital-common" }
vital-paper = { module = "com.ryderbelserion.vital:paper", version.ref = "vital-paper" }

# Common API
jetbrains = { module = "org.jetbrains:annotations", version.ref = "jetbrains" }

[bundles]
# Shared with the git submodules
shared = ["placeholderapi", "essentials", "vault"]

# Adventure API
adventure = ["kyori-api", "kyori-text", "kyori-logger"]

# Cloud Paper API
cloud-paper = ["cloud-extras", "cloud-paper"]