[versions]

# Spigot Team
spigot = "1.19.2-R0.1-SNAPSHOT"

# EngineHub Team
engine-hub = "7.0.0-SNAPSHOT"

# BG-Software Team
bg-skyblock-api = "2022.8.1"
bg-stacker-api = "2022.5"

# Bukkit
bukkit-bstats = "3.0.0"

# Placeholders
placeholder-api = "2.11.2"

# Misc Libraries
nbt-api = "2.10.0"
vault-api = "1.7"

ncp-api = "3.16.1-SNAPSHOT"

silk-spawners-api = "7.2.0"

oraxen-api = "master-SNAPSHOT"

# Claim Plugins
factions-uuid-api = "1.6.9.5-U0.6.9"

towny-api = "0.98.3.10"

plot-bom = "1.16"
plot-api = "6.10.1"

gp-api = "16.18"

[libraries]

# Paper Team
paper = { module = "io.papermc.paper:paper-api", version.ref = "spigot" }

# Spigot Team
spigot = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }

# EngineHub Team
bukkit-worldedit = { module = "com.sk89q.worldguard:worldguard-legacy", version.ref = "engine-hub" }
bukkit-worldguard = { module = "com.sk89q.worldedit:worldedit-bukkit", version.ref = "engine-hub" }

# OmeR Team
superior-skyblock = { module = "com.bgsoftware:SuperiorSkyblockAPI", version.ref = "bg-skyblock-api" }
wild-stacker = { module = "com.bgsoftware:WildStackerAPI", version.ref = "bg-stacker-api" }

# Bukkit
bukkit-bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bukkit-bstats" }

# Placeholders
placeholder-api = { module = "me.clip:placeholderapi", version.ref = "placeholder-api" }

# Misc Libraries
nbt-api = { module = "de.tr7zw:nbt-data-api", version.ref = "nbt-api" }
vault-api = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault-api" }

ncp-api = { module = "fr.neatmonster:nocheatplus", version.ref = "ncp-api" }

silk-spawners-api = { module = "de.dustplanet:silkspawners", version.ref = "silk-spawners-api" }

oraxen-api = { module = "com.github.oraxen:oraxen", version.ref = "oraxen-api" }

# Claim Plugins

grief-prevention-api = { module = "com.github.TechFortress:GriefPrevention", version.ref = "gp-api" }

plot-squared-bukkit = { module = "com.plotsquared:PlotSquared-Bukkit", version.ref = "plot-api"}

factions-uuid-api = { module = "com.massivecraft:Factions", version.ref = "factions-uuid-api" }

plot-squared-core = { module = "com.plotsquared:PlotSquared-Core", version.ref = "plot-api"}

plot-squared-bom = { module = "com.intellectualsites.bom:bom-1.18.x", version.ref = "plot-bom" }

towny-api = { module = "com.palmergames.bukkit.towny:towny", version.ref = "towny-api" }