name: '${name}'
main: '${group}.loader.CrazyEnchantmentsPlugin'
loader: '${group}.loader.CrazyEnchantmentsLoader'

version: '${version}'
api-version: '${apiVersion}'
description: '${description}'
website: '${website}'

folia-supported: true

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true